name: Build and upload wheels

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        compute_platform: ["cpu", "rocm5.3", "rocm5.4.2", "cu117", "cu118"]
        python_version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Maximise build space
        # Reduce the likelihood of ENOSPC.
        run: |
          echo 'Space available before:'
          echo '==========='
          df -h
          echo

          sudo rm -rf "$AGENT_TOOLSDIRECTORY" \
            /opt/ghc \
            /usr/local/lib/android \
            /usr/local/share/boost \
            /usr/share/dotnet \

          echo 'Space available after:'
          echo '==========='
          df -h
          echo

      - name: Clone repo
        uses: actions/checkout@v1

      - name: Set up Backblaze B2 CLI
        uses: wilsonzlin/setup-b2@v3

      - name: Build and upload wheel
        env:
          COMPUTE_PLATFORM: ${{ matrix.compute_platform }}
          PYTHON_VERSION: ${{ matrix.python_version }}
          PYTORCH_VERSION: "2.0.0"
        run: |
          if [[ "${{ matrix.python_version }}" == '3.11' ]] && [[ "${{ matrix.compute_platform }}" == rocm* ]]; then
            echo "ROCm packages are currently unavailable for Python 3.11 on x86-64, skipping"
            exit 0
          fi
          bash ./dev/packaging/build_wheel_in_docker.sh
          b2 authorize-account ${{ secrets.CICD_B2_KEY_ID }} ${{ secrets.CICD_B2_APPLICATION_KEY }}
          b2 sync --compareVersions size ./wheels/ b2://${{ secrets.CICD_B2_BUCKET_NAME }}/detectron2-neo/
